name: Build Code-OSS Portable (Windows x64)

on:
  workflow_dispatch: {}   # manual trigger
  push:
    tags:
      - 'v*.*.*'          # optional: build when you push a tag like v1.91.0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Point OSS build to Open VSX so Extensions view works

      - name: Configure Open VSX gallery
        shell: pwsh
        run: |
          $p = "product.json"
          if (Test-Path $p) {
            $j = Get-Content $p -Raw | ConvertFrom-Json
            # Add or replace the property safely
            if ($j.PSObject.Properties.Name -contains 'extensionsGallery') {
              $j.extensionsGallery = @{
                serviceUrl = "https://open-vsx.org/vscode/gallery"
                itemUrl    = "https://open-vsx.org/vscode/item"
              }
            } else {
              Add-Member -InputObject $j -NotePropertyName extensionsGallery -NotePropertyValue @{
                serviceUrl = "https://open-vsx.org/vscode/gallery"
                itemUrl    = "https://open-vsx.org/vscode/item"
              } -Force
            }
            $j | ConvertTo-Json -Depth 100 | Set-Content $p -Encoding UTF8
          }

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node18-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node18-

      - name: Install dependencies
        run: npm install

      - name: Package Windows x64 (minified)
        run: npm run gulp vscode-win32-x64-min
      - name: Debug - List packaged output
        shell: pwsh
        run: |
          Write-Host "=== Checking for build outputs ==="
          Get-ChildItem -Path . -Recurse -Include *.zip, *.exe -ErrorAction SilentlyContinue | 
            ForEach-Object { Write-Host "Found: $($_.FullName)" }
          Write-Host "`n=== Directory structure in build/ ==="
          if (Test-Path "./build") {
            Get-ChildItem -Path "./build" -Recurse -Depth 3 | 
              ForEach-Object { Write-Host $_.FullName }
          } else {
            Write-Host "No ./build directory found"
          }
      - name: Locate packaged folder and enable Portable Mode
        shell: pwsh
        id: portable
        run: |
          # Find the packaged executable anywhere in the repo
          $exe = Get-ChildItem -Recurse -File -Path . -Include "Code - OSS.exe","code-oss.exe","VSCode*.exe" | Select-Object -First 1
          if (-not $exe) { throw "Could not find packaged executable. Packaging may have failed earlier." }
       
          # The app folder is the EXE's parent directory
          $pkg = Split-Path -Parent $exe.FullName
       
          # Enable portable mode by creating 'data' next to the EXE
          New-Item -ItemType Directory -Path (Join-Path $pkg "data") -Force | Out-Null
       
          # Name the zip using tag or commit
          $ref = "${{ github.ref_name }}"
          if (-not $ref) { $ref = (git rev-parse --short HEAD) }
          $zipPath = "${{ github.workspace }}\code-oss-win32-x64-portable-$ref.zip"
       
          # Zip the whole packaged folder
          Compress-Archive -Path "$pkg\*" -DestinationPath $zipPath -Force
       
          # Expose the zip path to the next step
          Write-Output "zipPath=$zipPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: code-oss-win32-x64-portable
          path: ${{ steps.portable.outputs.zipPath }}
